name: Main workflow

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main


jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.14'

            - name: Install flake8
              run: pip install setuptools --upgrade flake8>=7.0.0 flake8-isort>=7.0.0

            - name: Run flake8
              run: python -m flake8 backend/


    push-docker-images:
        runs-on: ubuntu-latest
        needs:
          tests
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3 
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and push backend
              uses: docker/build-push-action@v5
              with:
                context: ./backend
                file: ./backend/Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/kittygram_backend:latest
            
            - name: Build and push frontend
              uses: docker/build-push-action@v5
              with:
                context: ./frontend
                file: ./frontend/Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/kittygram_frontend:latest

            - name: Build and push gateway
              uses: docker/build-push-action@v5
              with:
                context: ./nginx
                file: ./nginx/Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/kittygram_gateway:latest
              
    deploy:
      runs-on: ubuntu-latest
      needs:
        push-docker-images
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Create .env file locally
          run: |
            cat > .env << EOF
            # Database
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}

            # Backend
            DEBUG=${{ secrets.DEBUG }}
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}
            DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
            DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL }}
            DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}

            # Docker
            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            EOF

        - name: Copy files via ssh
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.DEPLOY_HOST }}
            username: ${{ secrets.DEPLOY_USER }}
            key: ${{ secrets.DEPLOY_SSH_KEY }}
            passphrase: ${{ secrets.DEPLOY_SSH_PASSPHRASE }}
            source: "docker-compose.production.yml,.env"
            target: "./app"

        - name: Run containers
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.DEPLOY_HOST }}
            username: ${{ secrets.DEPLOY_USER }}
            key: ${{ secrets.DEPLOY_SSH_KEY }}
            passphrase: ${{ secrets.DEPLOY_SSH_PASSPHRASE }}
            script: |
              cd ./app && \
              docker compose -f docker-compose.production.yml pull && \
              docker compose -f docker-compose.production.yml down && \
              docker compose -f docker-compose.production.yml up -d
    auto-tests:
      runs-on: ubuntu-latest
      needs: deploy
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.14'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest requests pyyaml

        - name: Create tests.yml with secrets
          run: |
            cat > tests.yml << EOF
            repo_owner: ${{ secrets.REPO_OWNER || 'LakeNotOcean' }}
            kittygram_domain: ${{ secrets.KITTYGRAM_DOMAIN }}
            dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
            EOF
      
        - name: Wait for application to be ready
          run: |
            echo "Waiting for application to start..."
            timeout 180 bash -c 'until curl -f -s ${{ secrets.KITTYGRAM_DOMAIN }} > /dev/null; do sleep 10; done'
            echo "Application is ready!"
            sleep 10

        - name: Run tests
          run: |
            pytest tests/ -v


    telegram-notify:
      runs-on: ubuntu-latest
      if: always()
      needs: 
        - tests
        - push-docker-images  
        - deploy
        - auto-tests
      steps:
        - name: Send Telegram message on commit
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: |
              ${{ format('Workflow {0}', github.workflow) }} completed!
              Repository: ${{ github.repository }}
              Commit: ${{ github.sha }}
              Message: ${{ github.event.head_commit.message }}
              
              Jobs status:
              - Tests: ${{ needs.tests.result }}
              - Push Docker: ${{ needs.push-docker-images.result }}
              - Deploy: ${{ needs.deploy.result }}
              - Auto Tests: ${{ needs.auto-tests.result }}
          
